# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Group the core client sources together into an interface library.
# This allows us to pull them into multiple builds like the dummy client.
add_library(mozillavpn-sources INTERFACE)

# VPN client include paths
set_property(TARGET mozillavpn-sources PROPERTY INTERFACE_INCLUDE_DIRECTORIES
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/addons
    ${CMAKE_CURRENT_SOURCE_DIR}/composer
    ${CMAKE_CURRENT_SOURCE_DIR}/hacl-star
    ${CMAKE_CURRENT_SOURCE_DIR}/hacl-star/kremlin
    ${CMAKE_CURRENT_SOURCE_DIR}/hacl-star/kremlin/minimal
    ${CMAKE_CURRENT_BINARY_DIR}
)

# Generated version header file
configure_file(version.h.in ${CMAKE_CURRENT_BINARY_DIR}/version.h)
target_sources(mozillavpn-sources INTERFACE ${CMAKE_CURRENT_BINARY_DIR}/version.h)

# VPN Client source files
target_sources(mozillavpn-sources INTERFACE
    addons/addon.cpp
    addons/addon.h
    addons/addonapi.cpp
    addons/addonapi.h
    addons/addonguide.cpp
    addons/addonguide.h
    addons/addoni18n.cpp
    addons/addoni18n.h
    addons/addonmessage.cpp
    addons/addonmessage.h
    addons/addonproperty.cpp
    addons/addonproperty.h
    addons/addonpropertylist.cpp
    addons/addonpropertylist.h
    addons/addontutorial.cpp
    addons/addontutorial.h
    addons/conditionwatchers/addonconditionwatcher.cpp
    addons/conditionwatchers/addonconditionwatcher.h
    addons/conditionwatchers/addonconditionwatcherfeaturesenabled.cpp
    addons/conditionwatchers/addonconditionwatcherfeaturesenabled.h
    addons/conditionwatchers/addonconditionwatchergroup.cpp
    addons/conditionwatchers/addonconditionwatchergroup.h
    addons/conditionwatchers/addonconditionwatcherjavascript.cpp
    addons/conditionwatchers/addonconditionwatcherjavascript.h
    addons/conditionwatchers/addonconditionwatcherlocales.cpp
    addons/conditionwatchers/addonconditionwatcherlocales.h
    addons/conditionwatchers/addonconditionwatchertime.cpp
    addons/conditionwatchers/addonconditionwatchertime.h
    addons/conditionwatchers/addonconditionwatchertimeend.h
    addons/conditionwatchers/addonconditionwatchertimestart.h
    addons/conditionwatchers/addonconditionwatchertriggertimesecs.cpp
    addons/conditionwatchers/addonconditionwatchertriggertimesecs.h
    addons/manager/addondirectory.cpp
    addons/manager/addondirectory.h
    addons/manager/addonindex.cpp
    addons/manager/addonindex.h
    addons/manager/addonmanager.cpp
    addons/manager/addonmanager.h
    appimageprovider.h
    applistprovider.h
    apppermission.cpp
    apppermission.h
    authenticationinapp/authenticationinapp.cpp
    authenticationinapp/authenticationinapp.h
    authenticationinapp/authenticationinapplistener.cpp
    authenticationinapp/authenticationinapplistener.h
    authenticationinapp/authenticationinappsession.cpp
    authenticationinapp/authenticationinappsession.h
    authenticationinapp/incrementaldecoder.cpp
    authenticationinapp/incrementaldecoder.h
    authenticationlistener.cpp
    authenticationlistener.h
    backendfailurewatcher.cpp
    backendfailurewatcher.h
    collator.cpp
    collator.h
    command.cpp
    command.h
    commandlineparser.cpp
    commandlineparser.h
    commands/commanddevice.cpp
    commands/commanddevice.h
    commands/commandlogin.cpp
    commands/commandlogin.h
    commands/commandlogout.cpp
    commands/commandlogout.h
    commands/commandui.cpp
    commands/commandui.h
    composer/composer.cpp
    composer/composer.h
    composer/composerblock.cpp
    composer/composerblock.h
    composer/composerblockbutton.cpp
    composer/composerblockbutton.h
    composer/composerblockorderedlist.cpp
    composer/composerblockorderedlist.h
    composer/composerblocktext.cpp
    composer/composerblocktext.h
    composer/composerblocktitle.cpp
    composer/composerblocktitle.h
    composer/composerblockunorderedlist.cpp
    composer/composerblockunorderedlist.h
    constants.cpp
    constants.h
    cryptosettings.cpp
    cryptosettings.h
    curve25519.cpp
    curve25519.h
    env.h
    errorhandler.cpp
    errorhandler.h
    externalophandler.cpp
    externalophandler.h
    filterproxymodel.cpp
    filterproxymodel.h
    fontloader.cpp
    fontloader.h
    frontend/navigator.cpp
    frontend/navigator.h
    frontend/navigatorreloader.cpp
    frontend/navigatorreloader.h
    glean/glean.h
    glean/glean.cpp
    glean/metrictypes.h
    glean/generated/metrics.h
    glean/generated/pings.h
    glean/private/event.cpp
    glean/private/event.h
    glean/private/ping.cpp
    glean/private/ping.h
    hacl-star/Hacl_Chacha20.c
    hacl-star/Hacl_Chacha20Poly1305_32.c
    hacl-star/Hacl_Curve25519_51.c
    hacl-star/Hacl_Poly1305_32.c
    hawkauth.cpp
    hawkauth.h
    hkdf.cpp
    hkdf.h
    imageproviderfactory.cpp
    imageproviderfactory.h
    inspector/inspectorhandler.cpp
    inspector/inspectorhandler.h
    inspector/inspectoritempicker.cpp
    inspector/inspectoritempicker.h
    inspector/inspectorutils.cpp
    inspector/inspectorutils.h
    inspector/inspectorwebsocketconnection.cpp
    inspector/inspectorwebsocketconnection.h
    inspector/inspectorwebsocketserver.cpp
    inspector/inspectorwebsocketserver.h
    ipaddress.cpp
    ipaddress.h
    ipaddresslookup.cpp
    ipaddresslookup.h
    itempicker.cpp
    itempicker.h
    keyregenerator.cpp
    keyregenerator.h
    leakdetector.cpp
    leakdetector.h
    localizer.cpp
    localizer.h
    logger.cpp
    logger.h
    loghandler.cpp
    loghandler.h
    logoutobserver.cpp
    logoutobserver.h
    logserializewatcher.cpp
    logserializewatcher.h
    main.cpp
    models/device.cpp
    models/device.h
    models/devicemodel.cpp
    models/devicemodel.h
    models/feature.cpp
    models/feature.h
    models/featuremodel.cpp
    models/featuremodel.h
    models/feedbackcategorymodel.cpp
    models/feedbackcategorymodel.h
    models/keys.cpp
    models/keys.h
    models/licensemodel.cpp
    models/licensemodel.h
    models/recentconnections.cpp
    models/recentconnections.h
    models/server.cpp
    models/server.h
    models/servercity.cpp
    models/servercity.h
    models/servercountry.cpp
    models/servercountry.h
    models/servercountrymodel.cpp
    models/servercountrymodel.h
    models/serverdata.cpp
    models/serverdata.h
    models/subscriptiondata.cpp
    models/subscriptiondata.h
    models/supportcategorymodel.cpp
    models/supportcategorymodel.h
    models/user.cpp
    models/user.h
    module.cpp
    module.h
    moduleholder.cpp
    moduleholder.h
    modulelist.h
    modules/modulevpn.cpp
    modules/modulevpn.h
    modules/modulevpn/captiveportal/captiveportal.cpp
    modules/modulevpn/captiveportal/captiveportal.h
    modules/modulevpn/captiveportal/captiveportaldetection.cpp
    modules/modulevpn/captiveportal/captiveportaldetection.h
    modules/modulevpn/captiveportal/captiveportaldetectionimpl.cpp
    modules/modulevpn/captiveportal/captiveportaldetectionimpl.h
    modules/modulevpn/captiveportal/captiveportalmonitor.cpp
    modules/modulevpn/captiveportal/captiveportalmonitor.h
    modules/modulevpn/captiveportal/captiveportalnotifier.cpp
    modules/modulevpn/captiveportal/captiveportalnotifier.h
    modules/modulevpn/captiveportal/captiveportalrequest.cpp
    modules/modulevpn/captiveportal/captiveportalrequest.h
    modules/modulevpn/captiveportal/captiveportalrequesttask.cpp
    modules/modulevpn/captiveportal/captiveportalrequesttask.h
    modules/modulevpn/captiveportal/taskcaptiveportallookup.cpp
    modules/modulevpn/captiveportal/taskcaptiveportallookup.h
    modules/modulevpn/commands/commandactivate.cpp
    modules/modulevpn/commands/commandactivate.h
    modules/modulevpn/commands/commanddeactivate.cpp
    modules/modulevpn/commands/commanddeactivate.h
    modules/modulevpn/commands/commandselect.cpp
    modules/modulevpn/commands/commandselect.h
    modules/modulevpn/commands/commandservers.cpp
    modules/modulevpn/commands/commandservers.h
    modules/modulevpn/commands/commandstatus.cpp
    modules/modulevpn/commands/commandstatus.h
    modules/modulevpn/connectionbenchmark/benchmarktask.cpp
    modules/modulevpn/connectionbenchmark/benchmarktask.h
    modules/modulevpn/connectionbenchmark/benchmarktaskping.cpp
    modules/modulevpn/connectionbenchmark/benchmarktaskping.h
    modules/modulevpn/connectionbenchmark/benchmarktasksentinel.h
    modules/modulevpn/connectionbenchmark/benchmarktasktransfer.cpp
    modules/modulevpn/connectionbenchmark/benchmarktasktransfer.h
    modules/modulevpn/connectionbenchmark/connectionbenchmark.cpp
    modules/modulevpn/connectionbenchmark/connectionbenchmark.h
    modules/modulevpn/connectionbenchmark/uploaddatagenerator.cpp
    modules/modulevpn/connectionbenchmark/uploaddatagenerator.h
    modules/modulevpn/connectionhealth.cpp
    modules/modulevpn/connectionhealth.h
    modules/modulevpn/controller.cpp
    modules/modulevpn/controller.h
    modules/modulevpn/controllerimpl.h
    modules/modulevpn/dnshelper.cpp
    modules/modulevpn/dnshelper.h
    modules/modulevpn/dnspingsender.cpp
    modules/modulevpn/dnspingsender.h
    modules/modulevpn/networkwatcher.cpp
    modules/modulevpn/networkwatcher.h
    modules/modulevpn/networkwatcherimpl.h
    modules/modulevpn/pinghelper.cpp
    modules/modulevpn/pinghelper.h
    modules/modulevpn/pingsender.cpp
    modules/modulevpn/pingsender.h
    modules/modulevpn/pingsenderfactory.cpp
    modules/modulevpn/pingsenderfactory.h
    modules/modulevpn/serverlatency.cpp
    modules/modulevpn/serverlatency.h
    modules/modulevpn/taskcontrolleraction.cpp
    modules/modulevpn/taskcontrolleraction.h
    modules/modulevpn/telemetry.cpp
    modules/modulevpn/telemetry.h
    mozillavpn.cpp
    mozillavpn.h
    networkmanager.cpp
    networkmanager.h
    networkrequest.cpp
    networkrequest.h
    notificationhandler.cpp
    notificationhandler.h
    platforms/dummy/dummyapplistprovider.cpp
    platforms/dummy/dummyapplistprovider.h
    platforms/dummy/dummynetworkwatcher.cpp
    platforms/dummy/dummynetworkwatcher.h
    platforms/dummy/dummypingsender.cpp
    platforms/dummy/dummypingsender.h
    productshandler.cpp
    productshandler.h
    profileflow.cpp
    profileflow.h
    purchasehandler.h
    purchasehandler.cpp
    purchaseiaphandler.cpp
    purchaseiaphandler.h
    purchasewebhandler.h
    purchasewebhandler.cpp
    qmlengineholder.cpp
    qmlengineholder.h
    quitwatcher.cpp
    quitwatcher.h
    releasemonitor.cpp
    releasemonitor.h
    rfc/rfc1112.cpp
    rfc/rfc1112.h
    rfc/rfc1918.cpp
    rfc/rfc1918.h
    rfc/rfc4193.cpp
    rfc/rfc4193.h
    rfc/rfc4291.cpp
    rfc/rfc4291.h
    rfc/rfc5735.cpp
    rfc/rfc5735.h
    serveri18n.cpp
    serveri18n.h
    settingsholder.cpp
    settingsholder.h
    signature.cpp
    signature.h
    simplenetworkmanager.cpp
    simplenetworkmanager.h
    statusicon.cpp
    statusicon.h
    task.h
    tasks/account/taskaccount.cpp
    tasks/account/taskaccount.h
    tasks/adddevice/taskadddevice.cpp
    tasks/adddevice/taskadddevice.h
    tasks/addon/taskaddon.cpp
    tasks/addon/taskaddon.h
    tasks/addonindex/taskaddonindex.cpp
    tasks/addonindex/taskaddonindex.h
    tasks/authenticate/taskauthenticate.cpp
    tasks/authenticate/taskauthenticate.h
    tasks/createsupportticket/taskcreatesupportticket.cpp
    tasks/createsupportticket/taskcreatesupportticket.h
    tasks/deleteaccount/taskdeleteaccount.cpp
    tasks/deleteaccount/taskdeleteaccount.h
    tasks/function/taskfunction.cpp
    tasks/function/taskfunction.h
    tasks/getfeaturelist/taskgetfeaturelist.cpp
    tasks/getfeaturelist/taskgetfeaturelist.h
    tasks/getsubscriptiondetails/taskgetsubscriptiondetails.cpp
    tasks/getsubscriptiondetails/taskgetsubscriptiondetails.h
    tasks/group/taskgroup.cpp
    tasks/group/taskgroup.h
    tasks/heartbeat/taskheartbeat.cpp
    tasks/heartbeat/taskheartbeat.h
    tasks/ipfinder/taskipfinder.cpp
    tasks/ipfinder/taskipfinder.h
    tasks/products/taskproducts.cpp
    tasks/products/taskproducts.h
    tasks/release/taskrelease.cpp
    tasks/release/taskrelease.h
    tasks/removedevice/taskremovedevice.cpp
    tasks/removedevice/taskremovedevice.h
    tasks/sendfeedback/tasksendfeedback.cpp
    tasks/sendfeedback/tasksendfeedback.h
    tasks/servers/taskservers.cpp
    tasks/servers/taskservers.h
    taskscheduler.cpp
    taskscheduler.h
    temporarydir.cpp
    temporarydir.h
    theme.cpp
    theme.h
    tutorial/tutorial.cpp
    tutorial/tutorial.h
    tutorial/tutorialstep.cpp
    tutorial/tutorialstep.h
    tutorial/tutorialstepbefore.cpp
    tutorial/tutorialstepbefore.h
    tutorial/tutorialstepnext.cpp
    tutorial/tutorialstepnext.h
    update/updater.cpp
    update/updater.h
    update/versionapi.cpp
    update/versionapi.h
    update/webupdater.cpp
    update/webupdater.h
    updaterequiredwatcher.cpp
    updaterequiredwatcher.h
    urlopener.cpp
    urlopener.h
    websocket/exponentialbackoffstrategy.cpp
    websocket/exponentialbackoffstrategy.h
    websocket/pushmessage.cpp
    websocket/pushmessage.h
    websocket/websockethandler.cpp
    websocket/websockethandler.h
)

# VPN Client UI resources
target_sources(mozillavpn-sources INTERFACE
    ui/license.qrc
    ui/resources.qrc
    ui/ui.qrc
    resources/certs/certs.qrc
    resources/public_keys/public_keys.qrc
)

# Signal handling for unix platforms
if(UNIX)
    target_sources(mozillavpn-sources INTERFACE
        signalhandler.cpp
        signalhandler.h
    )
endif()

# Sources for desktop platforms.
if(NOT CMAKE_CROSSCOMPILING)
    target_sources(mozillavpn-sources INTERFACE
        systemtraynotificationhandler.cpp
        systemtraynotificationhandler.h
        tasks/authenticate/desktopauthenticationlistener.cpp
        tasks/authenticate/desktopauthenticationlistener.h
        server/serverconnection.cpp
        server/serverconnection.h
        server/serverhandler.cpp
        server/serverhandler.h
    )
endif()
