# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
conda-wasm:
    description: "conda-pack the wasm environment"
    worker-type: b-linux
    worker:
        max-run-time: 3600
        docker-image: {in-tree: conda-base}
    treeherder:
        symbol: TL(conda-wasm)
    run:
        script: conda_pack_wasm.sh
        resources:
            - requirements.txt
            - taskcluster/scripts/requirements.txt
            - env-wasm.yml
        toolchain-alias: conda-wasm
        toolchain-artifact: public/build/conda-wasm.tar.xz
