# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    description: "Conda Pack an environment"
    worker:
        max-run-time: 14400
    worker-type: b-win2022
    run:
        resources:
            - env-windows.yml
            - requirements.txt
            - taskcluster/scripts/requirements.txt

windows-conda-pack: 
        fetches:
            fetch:
                - win-conda
        run:
            script: conda_pack_windows.ps1
            resources:
                - scripts/windows/conda-setup-xwin-sdk.ps1
                - scripts/windows/fetch-vsix-package.py
            toolchain-alias: conda-windows-x86_64
            toolchain-artifact: public/build/conda-windows.tar.xz
