# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    description: "Conda Pack the environment"
    fetches:
            fetch:
               - miniconda-osx
    worker:
        max-run-time: 14400
        env:
            QT_VERSION: "6.2.4"
    worker-type: b-macos
    run:
        script: conda_pack_ios.sh
        use-caches: false
        resources:
            - requirements.txt
            - env.yml
            - scripts/macos/conda_install_extras.sh
            - scripts/macos/conda_setup_qt.sh

conda-ios-x86_64-6.2.4:
        treeherder:
            symbol: "conda-ios-6.2"
        worker:
            env:
                QT_VERSION: "6.2.4"
        run:
            toolchain-alias: conda-ios-6.2.4
            toolchain-artifact: public/build/conda-ios.tar.gz

conda-ios-x86_64-6.6.0:
        treeherder:
            symbol: "conda-ios-6.6"
        worker:
            env:
                QT_VERSION: "6.6.0"
        run:
            toolchain-alias: conda-ios-6.6.0
            toolchain-artifact: public/build/conda-ios.tar.gz
