# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    worker:
        max-run-time: 3600
        docker-image: {in-tree: conda-base}
    worker-type: b-linux
    run:
        use-caches: []
        resources:
            - requirements.txt
            - taskcluster/scripts/requirements.txt

conda-osxcross:
    description: "conda-pack the osxcross environment"
    fetches:
            fetch:
               - macosx-sdk
    treeherder:
        symbol: TL(conda-osxcross)
    run:
        script: conda_pack_osxcross.sh
        resources:
            - env-apple.yml
        toolchain-alias: conda-osxcross
        toolchain-artifact: public/build/conda-osxcross.tar.xz

conda-windows-cross:
    description: "conda-pack the windows cross-compile environment"
    treeherder:
        symbol: TL(conda-windows-cross)
    run:
        script: conda_pack_wincross.sh
        resources:
            - env-windows.yml
            - scripts/windows/fetch-vsix-package.py
        toolchain-alias: conda-windows-cross
        toolchain-artifact: public/build/conda-windows-cross.tar.xz

conda-wasm:
    description: "conda-pack the wasm environment"
    treeherder:
        symbol: TL(conda-wasm)
    run:
        script: conda_pack_wasm.sh
        resources:
            - env-wasm.yml
        toolchain-alias: conda-wasm
        toolchain-artifact: public/build/conda-wasm.tar.xz
