# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
conda-android:
    description: "Conda Pack Android environment"
    worker:
        env: {}
        max-run-time: 14400
        docker-image: {in-tree: conda-base}
    worker-type: b-linux
    treeherder:
        symbol: TL(conda-android)
        platform: android/opt
    run:
        script: conda_pack_android.sh
        use-caches: []
        resources:
            - scripts/android/conda_setup_sdk.sh
            - scripts/android/conda_trim.sh
            - taskcluster/scripts/requirements.txt
            - android_sdk.txt
            - requirements.txt
            - env-android.yml
        toolchain-alias: conda-android
        toolchain-artifact: public/build/conda-android.tar.xz
