# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    description: "Conda Pack an environment"
    worker:
        env:
            QT_VERSION: "filled-by-transform: conda.py"
            ANDROID_ARCH: "filled-by-transform: conda.py"
        max-run-time: 14400
        docker-image: {in-tree: conda-base}
    worker-type: b-linux
    treeherder:
        symbol: "filled-by-transform: conda.py"
        platform: "filled-by-transform: conda.py"
    run:
        script: conda_pack_android.sh
        resources:
            - scripts/android/conda_setup_qt.sh
            - scripts/android/conda_setup_sdk.sh
            - scripts/android/conda_trim.sh
            - android_sdk.txt
            - requirements.txt
        toolchain-alias: "filled-by-transform: conda.py"
        toolchain-artifact: public/build/conda-android.tar.gz

# Note: for auto inflate to work 
# Tasks need to follow the naming scheme 
# conda-android-<android-arch>-<QT-Version>
# see transforms/conda.py

conda-android-arm64-6.6.0: {}
conda-android-arm64-6.2.4: {}
conda-android-armv7-6.2.4: {}
conda-android-x86-6.2.4: {}
conda-android-x86_64-6.2.4: {}
