# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    description: "Conda Pack an enviroment"
    worker:
        env:
            QT_VERSION: "6.2.4"
            ANDROID_ARCH: "arm64v8a"
        max-run-time: 14400

conda-android:
    run:
        script: conda_pack_android.sh
        resources:
            - scripts/android/conda_setup_qt.sh
            - scripts/android/conda_setup_sdk.sh
            - scripts/android/conda_trim.sh
            - android_sdk.txt
            - requirements.txt
        toolchain-alias: conda-android-arm64
        toolchain-artifact: public/build/conda-android-arm64.zip
    treeherder:
        symbol: TL(conda-android-arm64)
    worker-type: b-linux
    worker:
        docker-image: {in-tree: conda-base}