# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    description: "Conda Pack an enviroment"
    worker:
        env:
            QT_VERSION: "6.2.4"
            ANDROID_ARCH: "android_arm64_v8a"
        max-run-time: 14400
        docker-image: {in-tree: conda-base}
    worker-type: b-linux

    run:
        script: conda_pack_android.sh
        resources:
            - scripts/android/conda_setup_qt.sh
            - scripts/android/conda_setup_sdk.sh
            - scripts/android/conda_trim.sh
            - android_sdk.txt
            - requirements.txt
        toolchain-alias: conda-android-arm64
        toolchain-artifact: public/build/conda-android.tar.gz

conda-android-arm64:
    run:
        toolchain-alias: conda-android-arm64
    treeherder:
        symbol: TL(conda-android-arm64)
    worker-type: b-linux
    worker:
        env:
            QT_VERSION: "6.2.4"
            ANDROID_ARCH: "android_arm64_v8a"

conda-android-armeabi-v7a:
    run:
        toolchain-alias: conda-android-armeabi-v7a
    treeherder:
        symbol: TL(conda-android-armeabi-v7a)
    worker-type: b-linux
    worker:
        env:
            QT_VERSION: "6.2.4"
            ANDROID_ARCH: "android_armv7"

conda-android-x86:
    run:
        toolchain-alias: conda-android-x86
    treeherder:
        symbol: TL(conda-android-x86)
    worker-type: b-linux
    worker:
        env:
            QT_VERSION: "6.2.4"
            ANDROID_ARCH: "android_x86"

conda-android-x86_64:
    run:
        toolchain-alias: conda-android-x86_64
    treeherder:
        symbol: TL(conda-android-x86_64)
    worker-type: b-linux
    worker:
        env:
            QT_VERSION: "6.2.4"
            ANDROID_ARCH: "android_x86_64"