name: Download taskcluster artifact
descrion: Download artifacts from a Taskcluster task
inputs:
  taskid:
    description: 'Taskcluster task identifier to fetch artifacts from'
    required: true
    type: string
  artifact-name:
    description: "Artifact name to download from the task"
    required: true
    type: string
  path:
    description: Location to save the artifact
    default: ${{ github.workspace }}
    type: string

runs:
  using: "composite"
  steps:
    - name: Wait for taskcluster job
      id: taskgraph
      shell: bash
      run: |
        pip install requests
        ${{ github.action_path }}/await-taskcluster-status.py -t 3600 ${{ inputs.task-id }} | tee ${{ runner.temp }}/taskcluster-job-status.json
        echo run-id=$(jq '.runs[] | select(.state == "completed").runId' ${{ runner.temp }}/taskcluster-job-status.json) >> $GITHUB_OUTPUT

    - name: Download build artifact
      shell: bash
      env:
        TASKGRAPH_TASK_URL: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/${{ inputs.taskid }}
        TASKGRAPH_ARTIFACT: public%2Fbuild%2F${{ inputs.artifact-name }}
      run: |
        curl -sSL -o ${{ inputs.path }}/${{ inputs.artifact-name }} \
          ${TASKGRAPH_TASK_URL}/runs/${{ steps.taskgraph.outputs.run-id }}/artifacts/${TASKGRAPH_ARTIFACT}
