# A reusable workflow to build addons
on:
  workflow_call:
    inputs:
      test-addons-name:
        required: true
        type: string

permissions: {}

jobs:
  build-test-addons:
    name: Build Test Addons
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup addons cache
        id: addons-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: build-addons/
          key: test-addons-${{ hashFiles('addons/**', 'tests/functional/addons/**', 'scripts/addon/*.py', 'scripts/cmake/addons.cmake') }}

      - name: Install build dependencies
        if: steps.addons-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git submodule init
          git submodule update 3rdparty/i18n
          sudo apt-get update
          sudo apt-get install -y $(./scripts/linux/getdeps.py -b linux/debian/control)

      - name: Build test addons
        if: steps.addons-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p build-addons/
          cmake -S $(pwd)/tests/functional/addons -B build-addons/
          cmake --build build-addons/

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.test-addons-name }}
          path: build-addons/
