name: Put new Issues on the Board
on:
  issues:
    types: [opened]

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for new PRs
        run:  gh --repo mozilla-mobile/mozilla-vpn-client issue edit ${{ github.event.issue.number }} --add-project "Mozilla VPN Product Board"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
