name: Put new Issues on the Board
on:
  issues:
    types: [opened]
permissions:
  issues: write
  repository-projects: write

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Add incoming Issues to "Mozilla VPN Product Board"
        run:  gh --repo mozilla-mobile/mozilla-vpn-client issue edit ${{ github.event.issue.number }} --add-project "Mozilla VPN Product Board"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
