name: ssdlc-sbom

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  sbom:
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@3baba0c5ecad02b06380a4022b813dca5f5086c3
    with:
      sbom_name: ${{ github.event.release.tag_name || github.sha }}
